function [BW_out,properties] = filter3PieceRegions(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 15-Aug-2023
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
BW_out = bwpropfilt(BW_out,'Area',[22000, 25000]);

% Get properties.
properties = regionprops(BW_out, {'Area', 'Eccentricity'});
properties = struct2table(properties);
end